# Generated by Django 3.2.8 on 2021-10-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listgroups',
            old_name='name_groups',
            new_name='namegroups',
        ),
    ]
