# Generated by Django 3.2.8 on 2021-10-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_groups', '0002_rename_name_groups_listgroups_namegroups'),
        ('list_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listusers',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='list_groups.listgroups'),
            preserve_default=False,
        ),
    ]
